### ISSUE TITLE
Special fixes for 9.2 recipes

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#114]
1) custom recipes with optional reagent for all rank 7 legendaries

2) mark of the first one profession specific recipes

3) mark of the first one lego recipe handling
3.1) default to same profession for mark as lego
3.2) option to go with cheapest route
3.3) option to specify specific profession for mark

4) Validation of vendor price for feast’s vendor mat

**Comment by Heanthor** [comment]
@unlockedSound we need:

Empty Kettle of Stone Soup (id 187648) custom recipe for each path to fill the kettle ([comment](https://www.wowhead.com/item=187648/empty-kettle-of-stone-soup#comments))
Crafter's Mark of the First Ones (id 187742) custom recipe for all professions

**Comment by unlockedSound** [comment]
no longer relevant
