### ISSUE TITLE
darkmoon decks

### ISSUE THREAD

**Issue by Heanthor** [Heanthor/auctioneer-bot#24]
need to be added custom to recipe files

**Comment by unlockedSound** [comment]
recipe for 
blockades, tides, squalls, and fathoms
requires a 2,3,4,5,6,7,8, & Ace of the specific type
ex. Two of Fathoms
Fathoms
   Deck - itemID: 159125
      Cards - itemID: 153621-153627, 153605
Squalls
   Deck - itemID: 159126
      Cards - itemID: 153614-153620, 153604
Tides
   Deck - itemID: 159127
      Cards - itemID: 153607-153613, 153603
Blockades
   Deck - itemID: 159128
      Cards - itemID: 153628-153634, 153606

**Comment by unlockedSound** [comment]
so here's the key question... 1 spellID makes them all? So are we assigning unique spellIDs for each deck and mapping those?

(I'm going ahead and assuming this and having them do that: darkmoonFathoms, etc.)

**Comment by unlockedSound** [comment]
Completed and live. Bespoke recipe builder added decks.
