### ISSUE TITLE
Parse multiple commands as CFG

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#38]
Two possibilities:

either just a list of commands to be run in order received, such that 
`!r A !bg+ B !p C`
would give realm `A` and both the `bg+` and `p` results for their respective items `B` and `C`

alternatively we could actually parse this in the style of a programming language parser to allow inputs like
`!bg+ A !r B`
and logically parse and order this to give `bg+` of `A` on realm `B`, running the `!r` command first

**Comment by Heanthor** [comment]
On reed/parser branch

**Comment by Heanthor** [comment]
#23 explains the basic motivation for this

**Comment by unlockedSound** [comment]
not really worth it at this point, closing
