### ISSUE TITLE
!g Combination Commands

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#46]
Expand upon the introduction of `!g` with the ability to parse combinations of commands such as `!g !bg+ flask`giving !bg+ results for all flasks in the flask list.

**Comment by unlockedSound** [comment]
Based on ideas proposed in #23

**Comment by unlockedSound** [comment]
could be reinvisioned as a slash command... groups still interesting but is really just a shopping list at this point @Heanthor thoughts on opening a new ticket for allowing something like a BG plus against your shopping list? 

If so let me know and I'll write up and close this... if you think the idea is inane just close this out

**Comment by Heanthor** [comment]
There's vestiges of this still in the code, it was 3/4 built but never completed. I think sticking with a core of highly useful commands is better than providing lots of very similar ones. We also don't want to get in the business of curating shopping lists.

I think the seller's list type features which provide margins on shopping list items are essentially bg+ for SL, so let's stick with that.
