### ISSUE TITLE
Scrape S.P.A.R.E. Crate and spare parts from bnet api

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#50]
crates are made form parts and both are BoP

Handling for this must be added such that `!bg+ famine` prints properly.

**Comment by unlockedSound** [comment]
Assigning self till explicit list of item ids is added to the issue.

**Comment by unlockedSound** [comment]
Spare parts
itemID: 16684
S.P.A.R.E. Crate
itemID: 300291

**Comment by Heanthor** [comment]
@unlockedSound pretty sure the spare parts ID is missing a digit

**Comment by unlockedSound** [comment]
corrected

**Comment by Heanthor** [comment]
Spare crate id also is incorrect

**Comment by unlockedSound** [comment]
must have gotten spellID by accident

sorry

**Comment by Heanthor** [comment]
Thanks. And can you suggest an item to test this with bg+?

**Comment by Heanthor** [comment]
These items + ionized minnow (167562) are in the db.

**Comment by unlockedSound** [comment]
!bg+ famine
