### ISSUE TITLE
Valuation - Spare Parts 

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#51]
Look into means to generate value for `spare parts`

**Comment by unlockedSound** [comment]
mathematically should be rather straightforward 
just needs to work with
https://ptr.wowhead.com/spell=297107/famine-evaluator-and-snack-table
and
https://ptr.wowhead.com/spell=297080/mech-dowels-big-mech

**Comment by Heanthor** [comment]
In order to get a good printout for the famine evaluator feast, we might need a valuation for https://www.wowhead.com/item=167562/ionized-minnow#reagent-for too. That should probably be done as part of this ticket, or we should give it some value.

**Comment by unlockedSound** [comment]
Added - closing
