### ISSUE TITLE
Send messages out through bot

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#57]
Is there a way to have the bot post a message in all servers announcing updates?

Obviously don't want to overuse this, but could be a nice feature.

**Comment by Heanthor** [comment]
It definitely is possible, i'm not sure i feel comfortable with ith though

**Comment by unlockedSound** [comment]
Research use case and rules around the ability to announce to channels being forced from our side.

Also if implemented must allow users to easily opt out as soon as the feature is live.

**Comment by unlockedSound** [comment]
we effectively did this with the `!` commands when `/` was implemented. Could be done again.

**Comment by unlockedSound** [comment]
@Heanthor can probably close this but thoughts on building an easy way to do something like

`on the first command sent after the bot is updated post a message stating updates that are live`

do something like flag the server has received the message and then clear the flag when we do prod releases/updates

**Comment by Heanthor** [comment]
I don't want to do random push updates advertising features, but something which fires on the first ever usage of the bot in a server is definitely good. I also think discord might provide an API for a bot to have an official "welcome message" which we should use

**Comment by unlockedSound** [comment]
ok then closing this down as it's somewhat covered by #77
