### ISSUE TITLE
Scraper Tests

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#61]
ADD TESTS OMG TESTS ARE NEEDED SO BADLY!

In all seriousness, tests for edge cases as well as a variety of core recipes should be captured as tests to run against outcome file/scraped data before file is compiled.

**Comment by Heanthor** [comment]
This will require mocking the wowhead input, either by saving several html pages as files and testing against those, or constructing contrived pages for the bot to parse. This will be fragile considering if wowhead changes, there will be no way to guarantee the saved pages match the current structure.

The alternative is to do live "integration" tests where we test against the live wowhead. This is flimsy in a different way, it breaks any time wowhead is down or makes changes, but is more reflective of the issues the live bot will face.

**Comment by unlockedSound** [comment]
no longer valid
