### ISSUE TITLE
Scraper Parallelization for ID collection

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#63]
Parallelize the ID collection step of the scraper.

Can only be done post #58, likely only valuable once #59 is completed as well.

**Comment by Heanthor** [comment]
Notes about this: it could be parallelized by patch, which is logically the most simple way to do it. But, I think it could probably be more parallel to speed up runtime. If you had a worker pool or event loop to submit jobs to, each patch could have several tasks working in parallel as well.

The goal is to push the load on wowhead as high as possible before they start throttling us, to minimize runtime.

**Comment by unlockedSound** [comment]
no longer valid
