### ISSUE TITLE
8.2 item validation

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#64]
Confirm 8.2 recipes are causing no issues for users.

Notrious items may have been causing errors, though reason for issue was not confirmed at the time.

Research and create additional issues as needed.

**Comment by unlockedSound** [comment]
Notorious Combatant's Bow (id 167934)

at minimum this is broken. Building out a full list of notorious items

**Comment by unlockedSound** [comment]
- [ ] 294826
- [ ] 294768
- [ ] 294771
- [ ] 294786
- [ ] 294792
- [ ] 294795
- [ ] 294810
- [ ] 294801
- [ ] 294804
- [ ] 294798
- [ ] 294807
- [ ] 294825
- [ ] 294816
- [ ] 294819
- [ ] 294813
- [ ] 294765
- [ ] 294750
- [ ] 294753
- [ ] 294756
- [ ] 294762
- [ ] 294780
- [ ] 294843
- [ ] 294834
- [ ] 294846
- [ ] 294831
- [ ] 294837
- [ ] 294840
- [ ] 294777
- [ ] 294759
- [ ] 294783
- [ ] 294774
- [ ] 294789

**Comment by unlockedSound** [comment]
All Notorious appear to have built. Will examine file to determine if bow in particular had an issue and if so will rerun scrape to see if it can be reproduced.

**Comment by unlockedSound** [comment]
@Heanthor 
can you confirm for me what itemIDs are present in the recipe.json of the live bot for the `notorious combatant's bow`?

**Comment by Heanthor** [comment]
@unlockedSound `167935, 167936`

**Comment by unlockedSound** [comment]
Fixed and working on live. Definitely needs some further review but done.
