### ISSUE TITLE
Add Realm printout to time printout

### ISSUE THREAD

**Issue by Heanthor** [Heanthor/auctioneer-bot#67]
Change the time printout to include realm.

Example: `(data last updated 20m ago - Arthas-US)`

**Comment by unlockedSound** [comment]
@Heanthor this still feels like a nice improvement. Small but useful

**Comment by Heanthor** [comment]
I feel like this isn't actually needed anymore as all results that print cards include the realm in the item title, see:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/7563124/167269285-830ef1ff-9acb-42f9-99ee-4455e98f1ffb.png">
