### ISSUE TITLE
Decouple test and prod databases

### ISSUE THREAD

**Issue by Heanthor** [Heanthor/auctioneer-bot#69]
Obviously a big issue. Currently there is only one database shared between versions of the bot via config file. This worked okay in the past but now that valuations are live on both environments, I'm not able to modify the database as freely as I did before without affecting live traffic. Databases need to be separated so that changes can be made in lower environments totally free of conflicts.

- Add migration framework like Flyway or Sqitch.
- Possibly modify bnet scraper to write to migration .sql files instead of directly to postgres.
- Figure out a way to keep blizzard items consistent across environments.
- Consider splitting items or other constants (recipes) into separate database

**Comment by unlockedSound** [comment]
@Heanthor any updates or notes on this?

**Comment by Heanthor** [comment]
This is really funny to see, I totally forgot I ever wrote this but 1, 2, and 3 are all done, and 4 is taken care of by 2. Technically items are still a problem, but i have a script which copies them directly from dev -> prod which is better than nothing.. 🙃
