### ISSUE TITLE
Add disclaimer when data is bad

### ISSUE THREAD

**Issue by Heanthor** [Heanthor/auctioneer-bot#8]
Add disclaimer to !p and potentially !bg if very few auctions exist, as results might be meaningless.

**Comment by unlockedSound** [comment]
Only question is how little is too little data?

Many non-commodity items lack significant market presence. The primary goal of this is simply to help communicate the possibility that the data isn't great.

Could set specific values or could base it on parsing of historic data (which would be much preferred, something like 30%-50% lower than the average supply on the market).

**Comment by unlockedSound** [comment]
closing resolved through numerous methods
