### ISSUE TITLE
Additional Feature Request - Price Alerts

### ISSUE THREAD

**Issue by ninthwalker** [Heanthor/auctioneer-bot#85]
It would be great if this could also do price alerts.
So it could DM once per hour (configurable) if the current price is below what you set.

ie: 
!bgalert "Shal'dorei SIlk" 2g30s 1h

**Comment by Heanthor** [comment]
Hey, thanks for the comment, it's a great feature suggestion.
I would love to implement this in the future sometime, but right now auction data is retrieved from blizzard on demand (when someone requests an item, it first checks if there is new AH data and downloads it if necessary). 

This will be a big architectural change to potentially scan every server every hour. Along with that change though comes the ability to collect and analyze that AH data for trends, which is something we've planned to do with this tool as well.

**Comment by ninthwalker** [comment]
Thanks for the response. Did a little research and went ahead and created a bot to do alerts for my server for now.
If you guys ever add it to yours in the future, that would still be great as well, but you can close out this issue if you want. Thanks!

**Comment by unlockedSound** [comment]
@ninthwalker not sure if you ever say but we added a shopping list that does now allow for alert thresholds to be set. 

Closing issue
