### ISSUE TITLE
Battle pets

### ISSUE THREAD

**Issue by Heanthor** [Heanthor/auctioneer-bot#9]
Pets that aren't BOE by default aren't returned by blizzard's item api. Have to find a way to fill these in.

**Comment by unlockedSound** [comment]
pets are considered npc
wtf

item that makes a ironbound protodrake whelping:
https://www.wowhead.com/item=142087/ironbound-collar

the pet itself:
https://www.wowhead.com/npc=115139/ironbound-proto-whelp#summoned-by

what is the cage itself though? Is it an item, or some sort of token?

**Comment by unlockedSound** [comment]
HOLY SHIT I WAS RIGHT
https://www.wowhead.com/item=82800/pet-cage#comments

@Heanthor 
Look at those comments

this is some sort of base item that has a token of some sort attached to it for the individual pets. All caged pets probably have the same item number, but the cage has a set of unique values that define which pet it is plugged in.


Now wtf are we supposed to do with this...

**Comment by unlockedSound** [comment]
Additional evidence of token+cage theory

![506319ae-2f96-42ea-9575-d3976d6ff652](https://user-images.githubusercontent.com/18224436/47086567-e1c16a80-d1e7-11e8-950d-72a13b5ab550.png)
![887add45-e038-4cad-bf00-fbacc0e43b23](https://user-images.githubusercontent.com/18224436/47086568-e1c16a80-d1e7-11e8-8cbc-0d2184ff9dff.png)

**Comment by Heanthor** [comment]
Auctions for pets look like this

```json
{  
   "auc":1897172109,
   "item":82800,
   "owner":"Brutul",
   "ownerRealm":"Arthas",
   "bid":292998,
   "buyout":292998,
   "quantity":1,
   "timeLeft":"LONG",
   "rand":0,
   "seed":1972319872,
   "context":0,
   "modifiers":[  
      {  
         "type":3,
         "value":78
      },
      {  
         "type":4,
         "value":33554454
      },
      {  
         "type":5,
         "value":1
      },
      {  
         "type":6,
         "value":6303
      }
   ],
   "petSpeciesId":78,
   "petBreedId":22,
   "petLevel":1,
   "petQualityId":2
},
```

Battle pets from the "master list" api `/wow/pet/`  look like this
```json
    {
      "canBattle": true,
      "creatureId": 17254,
      "name": "Ash'ana",
      "family": "beast",
      "icon": "ability_mount_whitetiger",
      "qualityId": 4,
      "stats": {
        "speciesId": 1927,
        "breedId": 3,
        "petQualityId": 1,
        "level": 1,
        "health": 147,
        "power": 10,
        "speed": 9
      },
      "strongAgainst": [
        "critter"
      ],
      "typeId": 7,
      "weakAgainst": [
        "flying"
      ]
    },
```

SpeciesID appears to be unique, we can link the speciesID from auction result to the master pet list.

Other info here https://us.battle.net/forums/en/bnet/topic/20748634893

**Comment by unlockedSound** [comment]
FUCK BATTLE PETS
