### ISSUE TITLE
Crafter's mark support

### ISSUE THREAD

**Issue by Heanthor** [Heanthor/auctioneer-bot#99]
https://www.wowhead.com/item=183951/immortal-shard#reagent-for

These are BoP optional reagents, not normal items. But still a bg+ for this would be useful.

**Comment by unlockedSound** [comment]
wait, the scraper didn't get these? They have recipe versions from every crafting profession and also alternative recipe paths from BFA?! How do we not have these?

**Comment by unlockedSound** [comment]
done
